"""Generates the infra/build files (Dockerfile, docker-compose.yml, CI
config, dependency manifests) for the target stack -- the one deliberate
exception to `generator.py`'s "never show the LLM the original file" rule.
Infra files are declarative config, not business logic: there's little risk
of hidden behavior the graph didn't capture, and reconstructing exact
ports/volumes/health-checks/build-args purely from inferred facts is harder
and less reliable than editing the real file.

Runs *after* the other units generate (see `service.py`'s ordering), since
a Dockerfile/docker-compose.yml needs to know what services actually came
out of the migration, not just what existed before it.
"""

from __future__ import annotations

from atlaz.enhancement.models import RetrievedGuideline
from atlaz.llm.client import BaseLLMClient
from atlaz.migration.models import DependencyMapping, GeneratedFile, GeneratedUnit

_INSTRUCTIONS = (
    "You are an expert DevOps engineer updating a project's infrastructure and build files for a "
    "system migration. You are given the actual current content of every infra/build file, the "
    "overall migration plan, the services/units that resulted from the code migration, and the "
    "confirmed dependency mapping. Rules:\n"
    "1. Produce new versions of these files (or new files, e.g. one Dockerfile per new service) "
    "consistent with the migration plan and the units that were actually generated.\n"
    "2. Use the target dependency names/versions from the dependency mapping below -- do not "
    "invent package names or versions.\n"
    "3. Follow the enterprise guidelines below wherever they apply.\n"
    "4. Respond with a JSON object with one field, 'files': a list of objects, each with "
    "'file_path' and 'content' (the complete file contents -- no markdown fences, no commentary)."
)

_SCHEMA = {
    "type": "object",
    "properties": {
        "files": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"file_path": {"type": "string"}, "content": {"type": "string"}},
            },
        }
    },
}


class InfraMigrationAgent:
    def __init__(self, llm_client: BaseLLMClient) -> None:
        self.llm_client = llm_client

    def run(
        self,
        migration_request: str,
        plan_summary: str,
        current_files: dict[str, str],
        generated_unit_file_paths: dict[str, list[str]],
        dependency_mappings: list[DependencyMapping] | None = None,
        guidelines: list[RetrievedGuideline] | None = None,
    ) -> GeneratedUnit:
        guideline_text = "\n".join(f"- [{g.category}] {g.title}: {g.content}" for g in guidelines or [])
        current_files_text = "\n\n".join(f"### {path}\n{content}" for path, content in current_files.items())
        units_text = "\n".join(
            f"- {name}: {', '.join(paths)}" for name, paths in generated_unit_file_paths.items()
        )
        mapping_text = "\n".join(
            f"- {m.current_name} ({m.current_ecosystem}) -> {m.target_name} {m.target_version} ({m.target_ecosystem})"
            for m in dependency_mappings or []
        )
        prompt = (
            f"{_INSTRUCTIONS}\n\n"
            f"MIGRATION REQUEST:\n{migration_request}\n\n"
            f"MIGRATION PLAN:\n{plan_summary}\n\n"
            f"UNITS GENERATED BY THIS MIGRATION:\n{units_text or '(none)'}\n\n"
            f"CONFIRMED DEPENDENCY MAPPING:\n{mapping_text or '(none)'}\n\n"
            f"CURRENT INFRA/BUILD FILES:\n{current_files_text or '(none found)'}\n\n"
            f"ENTERPRISE GUIDELINES:\n{guideline_text or '(none retrieved)'}\n"
        )
        data = self.llm_client.complete_json(prompt, schema=_SCHEMA)
        files = [
            GeneratedFile(file_path=str(raw["file_path"]), content=str(raw.get("content", "")))
            for raw in data.get("files", [])
            if isinstance(raw, dict) and raw.get("file_path")
        ]
        return GeneratedUnit(
            unit_id="infra", unit_type="infra", name="Infrastructure & build",
            task_description="Regenerate infra/build files for the target stack.", files=files,
        )
