"""High-Level Design document generation.

Every section except the executive summary is rendered directly from
`ProjectFacts` -- no LLM involved, same "deterministic facts stay
deterministic" discipline the rest of the pipeline holds to. The executive
summary is the one LLM-synthesized section, and it is explicitly
instructed to use only the given facts and never invent a business
rationale the graph doesn't support -- mirroring Domain A's gap detector,
which never fabricates *why* the product exists either.
"""

from __future__ import annotations

from datetime import UTC, datetime

from atlaz.docgen.models import ProjectFacts
from atlaz.llm.client import BaseLLMClient

_SUMMARY_SCHEMA = {
    "type": "object",
    "properties": {"executive_summary": {"type": "string"}},
    "required": ["executive_summary"],
}


def generate_hld(facts: ProjectFacts, llm_client: BaseLLMClient) -> str:
    sections = [
        _header(facts),
        _executive_summary(facts, llm_client),
        _architecture_overview(facts),
        _business_capabilities(facts),
        _data_architecture(facts),
        _api_surface(facts),
        _security_overview(facts),
        _gaps_and_open_findings(facts),
    ]
    return "\n\n".join(s for s in sections if s)


def _header(facts: ProjectFacts) -> str:
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    languages = ", ".join(facts.repository.primary_languages) or "not detected"
    return (
        f"# High-Level Design — {facts.repository.name or facts.thread_id}\n\n"
        f"| | |\n|---|---|\n"
        f"| **Source run** | `{facts.thread_id}` |\n"
        f"| **Primary language(s)** | {languages} |\n"
        f"| **Generated** | {generated_at} |\n"
        f"| **Generated by** | AtlaZ (evidence-grounded; every claim below traces to the ingested repository) |"
    )


def _executive_summary(facts: ProjectFacts, llm_client: BaseLLMClient) -> str:
    capability_names = [c.name for c in facts.capabilities]
    service_names = [s.name for s in facts.services]
    gap_signals = [g for g in facts.gaps if g.category == "business_case"]
    gap_note = (
        "No business-case/vision signal was found in the codebase (README, commits, naming) -- "
        "this remains an external-only gap, not something code alone can answer."
        if gap_signals and gap_signals[0].still_open
        else ""
    )
    prompt = (
        "Write a 3-5 sentence executive summary for a High-Level Design document, using ONLY the "
        "facts below. Do not invent business strategy, market positioning, or rationale the facts "
        "don't support -- if the facts don't explain *why* the product exists, say the architecture "
        "and its extracted capabilities, not the business case, are what this document covers.\n\n"
        f"Repository: {facts.repository.name}\n"
        f"Primary languages: {', '.join(facts.repository.primary_languages) or 'unknown'}\n"
        f"Services/components ({len(service_names)}): {service_names}\n"
        f"Business capabilities identified from code ({len(capability_names)}): {capability_names}\n"
        f"Business-case signal: {'found' if gap_signals and gap_signals[0].signal_found else 'not found'}"
    )
    result = llm_client.complete_json(prompt, schema=_SUMMARY_SCHEMA)
    summary = result.get("executive_summary") or (
        f"This document describes the architecture of {facts.repository.name}, covering "
        f"{len(service_names)} service(s)/component(s) and {len(capability_names)} extracted "
        "business capability(ies), as reverse-engineered from the codebase."
    )
    body = f"## 1. Executive Summary\n\n{summary}"
    if gap_note:
        body += f"\n\n> **Note:** {gap_note}"
    return body


def _architecture_overview(facts: ProjectFacts) -> str:
    lines = ["## 2. System Architecture Overview", ""]
    if not facts.services:
        lines.append("_No service/component boundaries were derived from the codebase._")
        return "\n".join(lines)

    lines.append(f"{len(facts.services)} service(s)/component(s) were derived from folder topology and the module-level call graph.")
    lines.append("")
    lines.append("| Service | Files | Architecture style |")
    lines.append("|---|---|---|")
    for s in sorted(facts.services, key=lambda s: s.name):
        lines.append(f"| `{s.name}` | {s.module_count} | {s.architecture_style or 'unspecified'} |")

    if facts.service_dependencies:
        lines.append("")
        lines.append("### Dependency graph")
        lines.append("")
        lines.append("```mermaid")
        lines.append("graph TD")
        for dep in facts.service_dependencies:
            lines.append(f"    {_mermaid_id(dep.source)}[\"{dep.source}\"] -->|{dep.call_count} call(s)| {_mermaid_id(dep.target)}[\"{dep.target}\"]")
        lines.append("```")

    if facts.file_classification_counts:
        lines.append("")
        lines.append("### File composition")
        lines.append("")
        lines.append("| Classification | Files |")
        lines.append("|---|---|")
        for classification, count in sorted(facts.file_classification_counts.items(), key=lambda kv: -kv[1]):
            lines.append(f"| {classification} | {count} |")

    return "\n".join(lines)


def _business_capabilities(facts: ProjectFacts) -> str:
    lines = ["## 3. Business Capabilities & Workflows", ""]
    if not facts.capabilities:
        lines.append("_No business capabilities were clustered from the codebase._")
        return "\n".join(lines)

    lines.append("| Capability | Confidence | Cohesion | Modules | Needs review |")
    lines.append("|---|---|---|---|---|")
    for c in sorted(facts.capabilities, key=lambda c: -c.confidence):
        lines.append(f"| {c.name} | {c.confidence:.2f} | {c.cohesion_score:.2f} | {len(c.member_modules)} | {'yes' if c.needs_review else 'no'} |")

    if facts.workflows:
        lines.append("")
        lines.append("### Traced workflows")
        lines.append("")
        lines.append("Cross-domain call-graph traces from entry points, seeded by the capabilities above and the service boundaries in §2.")
        lines.append("")
        for w in facts.workflows:
            step_chain = " → ".join(w.steps) if w.steps else "(no steps recorded)"
            lines.append(f"- **{w.name}** (confidence {w.confidence:.2f}): {step_chain}")

    return "\n".join(lines)


def _data_architecture(facts: ProjectFacts) -> str:
    lines = ["## 4. Data Architecture", ""]
    if not facts.tables:
        lines.append("_No data entities (ORM models, migrations, or raw SQL schema) were detected._")
        return "\n".join(lines)
    lines.append(f"{len(facts.tables)} data entit(y/ies) detected across ORM models, migrations, and raw SQL schema.")
    lines.append("")
    lines.append("| Entity | Source | Confidence |")
    lines.append("|---|---|---|")
    for t in sorted(facts.tables, key=lambda t: t.name):
        lines.append(f"| `{t.name}` | {t.source_kind} | {t.confidence:.2f} |")
    return "\n".join(lines)


def _api_surface(facts: ProjectFacts) -> str:
    lines = ["## 5. API Surface", ""]
    if not facts.apis:
        lines.append("_No API routes were detected (no OpenAPI spec, no recognized route decorators)._")
        return "\n".join(lines)
    lines.append("| Method | Route | Handler | Source |")
    lines.append("|---|---|---|---|")
    for a in sorted(facts.apis, key=lambda a: (a.route, a.method)):
        lines.append(f"| {a.method} | `{a.route}` | {a.handler_ref or 'unresolved'} | {a.spec_source} |")
    return "\n".join(lines)


def _security_overview(facts: ProjectFacts) -> str:
    lines = ["## 6. Security Overview", ""]
    if not facts.security_controls:
        lines.append("_No auth/encryption/PII/audit-log patterns were detected — this is an absence of signal, not a confirmation of absence of controls._")
        return "\n".join(lines)
    by_type: dict[str, int] = {}
    for c in facts.security_controls:
        by_type[c.control_type] = by_type.get(c.control_type, 0) + 1
    lines.append("| Control type | Count |")
    lines.append("|---|---|")
    for control_type, count in sorted(by_type.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {control_type} | {count} |")
    regulation_hits = [c for c in facts.security_controls if c.regulation_hypothesis and c.regulation_hypothesis != "unknown"]
    if regulation_hits:
        lines.append("")
        lines.append("Possible regulatory relevance (hypotheses, not documented facts — see LLD for evidence):")
        for c in regulation_hits[:10]:
            lines.append(f"- `{c.location}`: {c.regulation_hypothesis} (confidence {c.regulation_confidence:.2f})" if c.regulation_confidence is not None else f"- `{c.location}`: {c.regulation_hypothesis}")
    return "\n".join(lines)


def _gaps_and_open_findings(facts: ProjectFacts) -> str:
    lines = ["## 7. Known Gaps & Open Findings", ""]
    any_content = False
    if facts.gaps:
        any_content = True
        for g in facts.gaps:
            lines.append(f"- **{g.category}**: {g.status}" + (" — still open" if g.still_open else " — resolved by a human reviewer"))
    if facts.conflicts:
        any_content = True
        lines.append("")
        lines.append(f"{len(facts.conflicts)} cross-domain conflict(s) detected between business rules and their implementation (see LLD §6 for detail).")
    low_confidence_rules = [r for r in facts.business_rules if r.needs_review]
    if low_confidence_rules:
        any_content = True
        lines.append(f"- {len(low_confidence_rules)} business rule(s) are below the confidence threshold and flagged `needs_review`.")
    if not any_content:
        lines.append("_No open gaps or unresolved conflicts were recorded for this run._")
    return "\n".join(lines)


def _mermaid_id(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name) or "root"
